version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:31112

functions:

  generate-password:
    lang: python3-http
    handler: ./functions/generate-password
    image: ${DOCKER_USER}/cofrap-generate-password:latest
    secrets:
      - db-host
      - db-port
      - db-name
      - db-user
      - db-password
    environment:
      write_debug: true

  generate-2fa:
    lang: python3-http
    handler: ./functions/generate-2fa
    image: ${DOCKER_USER}/cofrap-generate-2fa:latest
    secrets:
      - db-host
      - db-port
      - db-name
      - db-user
      - db-password
      - totp-encryption-key
    environment:
      write_debug: true

  authenticate:
    lang: python3-http
    handler: ./functions/authenticate
    image: ${DOCKER_USER}/cofrap-authenticate:latest
    secrets:
      - db-host
      - db-port
      - db-name
      - db-user
      - db-password
      - totp-encryption-key
    environment:
      write_debug: true
